#include "C:\moaproj\V47.10\src\INCLUDE\impresio.h"
#include "C:\moaproj\V47.10\src\INCLUDE\ofbdefs.h"
#include "C:\moaproj\V47.10\src\INCLUDE\csr.h"
#include "C:\moaproj\V47.10\src\INCLUDE\descuento.h"
#include "C:\moaproj\V47.10\src\INCLUDE\tesoro.h"
#include "C:\moaproj\V47.10\src\INCLUDE\commdef.h"
#include "C:\moaproj\V47.10\src\INCLUDE\Hcommstd.h"
