#include "C:\moaproj\V47.10\src\INCLUDE\ofbdefs.h"
#include "C:\moaproj\V47.10\src\INCLUDE\commdef.h"
#include "C:\moaproj\V47.10\src\INCLUDE\Hcommstd.h"
#include "hcomm.h"
#include "C:\moaproj\V47.10\src\INCLUDE\csr.h"
