#include "C:\moaproj\V47.10\src\INCLUDE\ofbdefs.h"
#include "C:\moaproj\V47.10\src\INCLUDE\commdef.h"
#include "hcomm.h"
#include "batch.h"
#include "C:\moaproj\V47.10\src\INCLUDE\giros.h"
#include "csmsgdef.h"
