#include "C:\moaproj\V47.10\src\INCLUDE\drv.h"
#include "C:\moaproj\V47.10\src\INCLUDE\base.h"
#include "C:\MOA\src\include\ofb\cdserdef.h"
#include "C:\moaproj\V47.10\src\INCLUDE\gsp.h"
#include "C:\moaproj\V47.10\src\INCLUDE\ofbdefs.h"
#include "C:\moaproj\V47.10\src\INCLUDE\impresio.h"
#include "C:\moaproj\V47.10\src\INCLUDE\csr.h"
#include "C:\moaproj\V47.10\src\INCLUDE\Sap.h"
#include "C:\moaproj\V47.10\src\INCLUDE\tesoro.h"
#include "C:\moaproj\V47.10\src\INCLUDE\Hcommstd.h"
#include "C:\moaproj\V47.10\src\INCLUDE\presupuesto.h"
#include "C:\moaproj\V47.10\src\INCLUDE\descuento.h"
#include "C:\moaproj\V47.10\src\INCLUDE\pickdrv.h"
#include "C:\moaproj\V47.10\src\INCLUDE\bonif.h"	
#define REST_REG "REGIONES:"
#define REST_PRV "PROVINCIAS:"
#define REST_SUC "SUCURSALES:"
#define REST_CLI "CLIENTES:"
#define REST_UP "UP:"
#define REST_PRD "PRODUCTOS:"
#define REST_ESP "ESPECIES:"
