#include "C:\moaproj\V47.10\src\INCLUDE\descuento.h"
#include "C:\moaproj\V47.10\src\INCLUDE\giros.h"
#include "hcomm.h"
#include "C:\moaproj\V47.10\src\INCLUDE\ofbdefs.h"
#include "C:\moaproj\V47.10\src\INCLUDE\impresio.h"
#include "C:\moaproj\V47.10\src\INCLUDE\csr.h"
