#include "C:\moaproj\V47.10\src\INCLUDE\ofbdefs.h"
#include "tlr.h"
#include "C:\MOA\src\include\ofb\cdserdef.h"
#include "C:\moaproj\V47.10\src\INCLUDE\base.h"
#include "C:\moaproj\V47.10\src\INCLUDE\sucuvirt.h"
#define MENSAJES_CIERRE "SI"
