#include "C:\moaproj\V47.10\src\INCLUDE\sucuvirt.h"
#include "C:\moaproj\V47.10\src\INCLUDE\commdef.h"
#include "C:\moaproj\V47.10\src\INCLUDE\Hcommstd.h"
#include "C:\moaproj\V47.10\src\INCLUDE\ofbdefs.h"
#include "hcomm.h"
#include "tlr.h"
#include "C:\moaproj\V47.10\src\INCLUDE\base.h"
#include "C:\MOA\src\include\ofb\cdserdef.h"
#include "C:\moaproj\V47.10\src\INCLUDE\drv.h"
#include "C:\moaproj\V47.10\src\INCLUDE\giros.h"
#include "C:\moaproj\V47.10\src\INCLUDE\Sap.h"
#include "C:\moaproj\V47.10\src\INCLUDE\impresio.h"
#define MENSAJES_CIERRE "SI"
#define STATUS_UP_ANULADO 100
