#include "C:\moaproj\V47.10\src\INCLUDE\ofbdefs.h"
#include "C:\MOA\src\include\ofb\desktop.h"
#include "C:\moaproj\V47.10\src\INCLUDE\color.h"
#include "cl.h"
#include "C:\moaproj\V47.10\src\INCLUDE\base.h"
#include "C:\moaproj\V47.10\src\INCLUDE\giros.h"
