/****x* Pendientes de agrupacin/DEF:includes:batch
* NOMBRE
*   DEF:includes:batch
* DESCRIPCION
*   Comportamiento del objeto (obligatorio)
* IMPACTOS
*   Otros objetos que debern ser analizados al modificar el objeto actual
* REFERENCIADO POR
*   Objetos que llaman al objeto documentado (obligatorio)
* DOCUMENTACION
*   Documentacin relevante que deber ser actualizada por la modificacin de la rutina
* SOURCE
*/

#include "C:\moaproj\V47.10\src\INCLUDE\base.h"

;Reentry function for batch rt                 (1=supported, 0=not supported)
#define		BATCH_REENTRY  0

/*******/
