/****x* Pendientes de agrupacin/DEF:include:DDS
* NOMBRE
*   DEF:include:DDS
* DESCRIPCION
*   Comportamiento del objeto (obligatorio)
* ENTRADAS
*   Parmetros de entrada de la rutina, sean argumentos o campos que tiene en cuenta
* SALIDAS
*   Campos modificados como resultado o returns cuyos valores sean no triviales
* IMPACTOS
*   Otros objetos que debern ser analizados al modificar el objeto actual
* REFERENCIADO POR
*   Objetos que llaman al objeto documentado (obligatorio)
* DOCUMENTACION
*   Documentacin relevante que deber ser actualizada por la modificacin de la rutina
* SOURCE
*/
#include "C:\moaproj\V47.10\src\INCLUDE\base.h"
#include "C:\moaproj\V47.10\src\INCLUDE\color.h"
#include "C:\MOA\src\include\ofb\field.h"
#define LOGIN_ID_SIZE 8

/*******/
