/****x* Pendientes de agrupacin/DEF:include:NACALC
* NOMBRE
*   DEF:include:NACALC
* DESCRIPCION
*   Comportamiento del objeto (obligatorio)
* ENTRADAS
*   Parmetros de entrada de la rutina, sean argumentos o campos que tiene en cuenta
* SALIDAS
*   Campos modificados como resultado o returns cuyos valores sean no triviales
* IMPACTOS
*   Otros objetos que debern ser analizados al modificar el objeto actual
* REFERENCIADO POR
*   Objetos que llaman al objeto documentado (obligatorio)
* DOCUMENTACION
*   Documentacin relevante que deber ser actualizada por la modificacin de la rutina
* SOURCE
*/
#define COL1 		SB0
#define COL2 		SB1
#define COL3 		SB2
#define VIEW 		SB3
#define GRAPH 		SB4
#define PRINT 		SB5
#define COPY 		SB6
#define PASTE 		SB7

#define FUR_VAL		0
#define PRE_VAL		1
#define TERM		2
#define INTEREST	3
#define CD_PEN		4
#define IRA_AV		5
#define IRA_DIS		6
#define IRA_PEN		7
#include "C:\MOA\src\include\ofb\field.h"

/*******/
