#include "C:\moaproj\V47.10\src\INCLUDE\csr.h"
#include "C:\moaproj\V47.10\src\INCLUDE\ofbdefs.h"
#include "C:\moaproj\V47.10\src\INCLUDE\giros.h"
#include "C:\moaproj\V47.10\src\INCLUDE\Hcommstd.h"
#include "C:\moaproj\V47.10\src\INCLUDE\sucuvirt.h"
#include "C:\moaproj\V47.10\src\INCLUDE\impresio.h"
#include "C:\moaproj\V47.10\src\INCLUDE\tesoro.h"
#include "C:\moaproj\V47.10\src\INCLUDE\pickdrv.h"
