#include "C:\moaproj\V47.10\src\INCLUDE\sucuvirt.h"
#include "C:\moaproj\V47.10\src\INCLUDE\ofbdefs.h"
#include "C:\moaproj\V47.10\src\INCLUDE\impresio.h"
#include "C:\moaproj\V47.10\src\INCLUDE\csr.h"
#include "C:\moaproj\V47.10\src\INCLUDE\pickdrv.h"
#include "C:\moaproj\V47.10\src\INCLUDE\drv.h"
#include "C:\moaproj\V47.10\src\INCLUDE\Hcommstd.h"
#include "C:\moaproj\V47.10\src\INCLUDE\giros.h"
#include "C:\moaproj\V47.10\src\INCLUDE\tesoro.h"
#include "C:\MOA\src\include\ofb\cdserdef.h"
#include "C:\moaproj\V47.10\src\INCLUDE\descuento.h"
#include "C:\moaproj\V47.10\src\INCLUDE\presupuesto.h"
#include "C:\moaproj\V47.10\src\INCLUDE\bonif.h"
#include "C:\moaproj\V47.10\src\INCLUDE\reporte.h"
#define MONEDA_SF1_PROV_GENERICA	"9"
#define MAYORISTAS 8
#define REEMP_MAX_MP 6
#define PICKOP_SORT 4
#define SELECCION_TODAS_SUC "TODAS"
#define EXCLUSION "E"
#define INCLUSION "I"
#define REST_PRD "PRODUCTOS:"
#define REST_ESP "ESPECIES:"
#define DESCTO_SERVICIO "SERVICIOS:"
#define PICKOP_SEARCH 3
#define BROWSER_CAPTION	"Buscar"
