#include "C:\moaproj\V47.10\src\INCLUDE\ofbdefs.h"
#include "C:\moaproj\V47.10\src\INCLUDE\drv.h"
#include "C:\moaproj\V47.10\src\INCLUDE\admin_dt.h"
#include "C:\moaproj\V47.10\src\INCLUDE\base.h"
#include "C:\moaproj\V47.10\src\INCLUDE\csr.h"
#include "C:\moaproj\V47.10\src\INCLUDE\pickdrv.h"
#include "C:\moaproj\V47.10\src\INCLUDE\giros.h"
#include "C:\moaproj\V47.10\src\INCLUDE\commdef.h"
#include "C:\moaproj\V47.10\src\INCLUDE\descuento.h"
#include "C:\moaproj\V47.10\src\INCLUDE\impresio.h"
#define REST_REG "REGIONES:"
#define REST_PRV "PROVINCIAS:"
#define REST_SUC "SUCURSALES:"
#define REST_CLI "CLIENTES:"
#define REST_UP "UP:"

